name: HeadDrops
version: 2.1
authors: [X1machinemaker1X, pizzafreak08]
main: me.x1machinemaker1x.headdrops.HeadDrops
description: Make hostile Mobs and Players drop their Heads!
commands:
    headdrops:
      description: Main command for HeadDrops
      aliases: [hd]